name: MGameBase
main: MGameBase\MGameBase
version: 52
api:
 - 1.0.0
 - 2.0.0
 - 3.0.0
 - 3.0.0-ALPHA1
 - 3.0.0-ALPHA2
 - 3.0.0-ALPHA3
 - 3.0.0-ALPHA4
 - 3.0.0-ALPHA5
 - 3.0.0-ALPHA6
 - 4.0.0
 - 5.0.0
 - 6.0.0
 - 7.0.0
 - 8.0.0
 - 9.0.0
load: POSTWORLD
author: Matt
description: A Game Base

permissions:
 MGameBase.*:
  default: op
  description: Allows to control all of functions in MGameBase
  children:
   MGameBase.command.*:
    default: op
    description: Allows to use all of commands in MGameBase
    children:
     MGameBase.command.mgb:
      default: true
      description:
     MGameBase.command.friend:
      description:
      default: true
     MGameBase.command.mail:
      description:
      default: true
     MGameBase.command.lang:
      description: 
      default: true
     MGameBase.command.hide:
      description: 
      default: true
     MGameBase.command.show:
      description: 
      default: true
